#!/bin/bash

dpkg-query -W -f='${Status}' mysql-server php5-mysql > /dev/null 2>&1
case $? in
0)
	echo $1 is installed
	;;
1)
	echo $1 is not installed
	export DEBIAN_FRONTEND="noninteractive"
	sudo debconf-set-selections <<< "mysql-server mysql-server/root_password password qwerty"
	sudo debconf-set-selections <<< "mysql-server mysql-server/root_password_again password qwerty"
	apt-get install -y mysql-server php5-mysql;
	echo "MySQL server on installeeritud!";
	;;
2)
	echo Error
	;;
esac

