#!/bin/bash

for kasutaja in $(ls /home)
do

ls /home/$kasutaja | grep public > /dev/null

if [ $? -eq 1 ]; then
	mkdir /home/$kasutaja /public && chown -R $kasutaja :$kasutaja /home/$kasutaja /home/$kasutaja /public && chmod 751 /home/$kasutaja /public
	if [ $? -eq 0 ]; then
	echo "Kasutaja nimega $kasutaja on juba kodukaustana (public) loodud."
	ls -la /home/$kasutajanimi
else
	echo "Probleem kasutaja $kasutaja public lisamisega"
	echo "Probleem: $?"
	fi
else
echo "Kasutaja nimega $kasutaja on juba public'una olemas"
fi

done
